import Head from "next/head";
import Image from "next/image";
import Counter from "../components/redux/component/Counter";
import StorageFunc from "../components/LocalStorage/StorageFunc";
import Link from "next/link";

export default function Home() {
  return (
    <div className="w-screen h-screen items-center justify-center flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <Counter />
          <StorageFunc />
          <Link href="./ssr/">
            <p>SSR : POST Page</p>
          </Link>
          <Link href="./ssg/">
            <p>SSG : POST Page</p>
          </Link>
          <Link href="./swr/">
            <p>SWR : POST Page</p>
          </Link>
        </div>
      </main>
    </div>
  );
}
